### ISSUE TITLE
Emoji aren't decoded properly

### ISSUE THREAD

**Issue by llimllib** [nedbat/dinghy#12]
The final comment here:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/7150/184218612-ac5e72a2-5b43-4482-a2dd-81bc13722f58.png">

Ought to be a rocketship instead of `ðŸš€`:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/7150/184218689-0aa6f58e-6bc8-4708-a757-3edb4f9a3bd0.png">

**Comment by llimllib** [comment]
Update: the rocket emoji is in the document, but the document is not being displayed as utf-8 encoded (I don't really know why?)

Anyway, the upshot is that adding `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` makes the rocket display properly

**Comment by nedbat** [comment]
This is now released as [dinghy 0.13.2](https://pypi.org/project/dinghy/0.13.2/).
