### ISSUE TITLE
Potentially use UUID in digest titles in config file to create RSS feed or Blog

### ISSUE THREAD

**Issue by nitinthewiz** [nedbat/dinghy#14]
Hi,

I have a feature request - 

Would it be possible to allow a UUID or a random value generator function to name the digests, where the config in dinghy.yaml says the following? 

```
digests:
  - digest: lastweek.html
```

Potential replacement - 

```
digests:
  - digest: {UUID}.html
```

This would allow for the generated HTML file to not be overwritten. When run weekly, it can be used to create an RSS feed or blog - a historical record of the activity digests. 

A flaw in this approach - if the config file has multiple digests in it, like the example, they'll each have a distinct UUID (or a common UUID which would overwrite the file) which wouldn't be descriptive of the content of the digest.

So, another way to do this would be to modify `make_digests_from_config()` under `digest.py` to add a output filename parameter, which would be appended to lastweek.html, hotnews.html etc, like so - `lastweek_20220815.html`, `hotnews_20220815.html` (assuming the user sends in the current date).

I saw the dinghy_sample project and the URL you've linked to. It looks very nice!

**Comment by nedbat** [comment]
I'm wondering if it wouldn't be simpler to just let a later step in the publishing pipeline rename the files or move them to the best place?

**Comment by nitinthewiz** [comment]
I had not seen the use of dinghy with github actions. That does definitely make it simple to rename the files automatically. We don't really need to add this to dinghy if you want to keep the tool small by design 😃

**Comment by nedbat** [comment]
Thanks, I think that would be for the best.
