### ISSUE TITLE
Feature Request: Specify `since` with specific date

### ISSUE THREAD

**Issue by JeffersGlass** [nedbat/dinghy#26]
It would be nice to be able to run a dinghy report with updates from a specific date. My use cases are:

- I've just returned from a long time away from a project, and would like a summary from all information since the last time I know I looked at it
- Running a digest of all updates since the last release.

Alternatively, the ability to use `since: release/{release-name}` or `since: commit/{commit-hash}` or `since: tag/{tag}` would also work for my purposes. I don't know if any of the above are simpler/harder to implement given the GitHub API.

**Comment by nedbat** [comment]
These are interesting ideas, thanks! The simplest approach might be to use different fields than `since` for these other ways to indicate a point in time: `since-release: {release-name}`, `since-commit: {ref}`, `since-tag: {ref}`?

**Comment by nedbat** [comment]
Maybe I'm wrong, but this also seems like it would be useful as a command-line argument, and not so much in the yaml, since you wouldn't be using the same point in time multiple times. It's for a one-off, correct?

**Comment by nedbat** [comment]
`since=DATE` and a command-line `--since=SINCE` option are implemented in commit 7dd9b7b.

**Comment by nedbat** [comment]
This is now available as [dinghy 1.3.0](https://pypi.org/project/dinghy/1.3.0/).

**Comment by JeffersGlass** [comment]
Fantastic! Thank you so much @nedbat !
