### ISSUE TITLE
--since is ignored when called without a config

### ISSUE THREAD

**Issue by pquentin** [nedbat/dinghy#35]
Very nice tool, thanks! Handy after coming back from vacation!

The default value of one week is used instead. Passing `since=since` in this line fixes the issue locally:

https://github.com/nedbat/dinghy/blob/e733bdf24229c4f5610d4d5a022bd414bd3a9919/src/dinghy/cli.py#L60

**Comment by nedbat** [comment]
Thanks, this is now fixed in Dinghy 1.3.1.
